{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "import requests\n",
    "import json\n",
    "import pandas as pd\n",
    "from pprint import pprint\n",
    "from census import Census\n",
    "from us import states\n",
    "import gmaps\n",
    "\n",
    "\n",
    "#Census API Key\n",
    "from config import api_key\n",
    "c = Census(api_key, year=2017)\n",
    "c2= Census(api_key, year=2011)\n",
    "\n",
    "# Gmaps\n",
    "from config import gkey\n",
    "import gmaps.geojson_geometries\n",
    "gmaps.configure(api_key=gkey)\n",
    "\n",
    "# Matplotlib colors\n",
    "import matplotlib\n",
    "from matplotlib import cm\n",
    "from matplotlib.cm import viridis\n",
    "from matplotlib.cm import coolwarm\n",
    "from matplotlib.colors import to_hex\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>States</th>\n",
       "      <th>Median Income</th>\n",
       "      <th>Home Value</th>\n",
       "      <th>Bachelors Degree</th>\n",
       "      <th>Population</th>\n",
       "      <th>Divorce</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Alabama</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Alaska</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Arizona</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Arkansas</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>California</td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "      <td></td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       States Median Income Home Value Bachelors Degree Population Divorce\n",
       "0     Alabama                                                             \n",
       "1      Alaska                                                             \n",
       "2     Arizona                                                             \n",
       "3    Arkansas                                                             \n",
       "4  California                                                             "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "states = [\"Alabama\", \"Alaska\", \"Arizona\",\"Arkansas\",\"California\",\"Colorado\",\"Connecticut\",\"Delaware\",\"District of Columbia\",\"Florida\",\"Georgia\",\n",
    "          \"Hawaii\",\"Idaho\",\"Illinois\",\"Indiana\",\"Iowa\",\"Kansas\",\"Kentucky\",\"Louisiana\",\"Maine\",\"Maryland\",\"Massachusetts\",\n",
    "          \"Michigan\",\"Minnesota\",\"Mississippi\",\"Missouri\",\"Montana\",\"Nebraska\",\"Nevada\",\"New Hampshire\",\"New Jersey\",\n",
    "          \"New Mexico\",\"New York\",\"North Carolina\",\"North Dakota\",\"Ohio\",\"Oklahoma\",\"Oregon\",\"Pennsylvania\",\"Rhode Island\",\n",
    "          \"South Carolina\",\"South Dakota\",\"Tennessee\",\"Texas\",\"Utah\",\"Vermont\",\"Virginia\",\"Washington\",\"West Virginia\",\"Wisconsin\",\n",
    "          \"Wyoming\"\n",
    "]\n",
    "\n",
    "df = pd.DataFrame(data={\"States\": states})\n",
    "df[\"Median Income\"] = \"\"\n",
    "df[\"Home Value\"] = \"\"\n",
    "df[\"Bachelors Degree\"] = \"\"\n",
    "df[\"Population\"] = \"\"\n",
    "df[\"Divorce\"] = \"\"\n",
    "\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>State</th>\n",
       "      <th>Population</th>\n",
       "      <th>Bachelors Rate</th>\n",
       "      <th>HS Diploma Rate</th>\n",
       "      <th>Unemployment Rate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Alabama</td>\n",
       "      <td>4874747.0</td>\n",
       "      <td>25.60</td>\n",
       "      <td>92.22</td>\n",
       "      <td>5.81</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Alaska</td>\n",
       "      <td>739795.0</td>\n",
       "      <td>29.35</td>\n",
       "      <td>99.27</td>\n",
       "      <td>7.25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Arizona</td>\n",
       "      <td>7016270.0</td>\n",
       "      <td>29.43</td>\n",
       "      <td>91.37</td>\n",
       "      <td>5.77</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Arkansas</td>\n",
       "      <td>3004279.0</td>\n",
       "      <td>23.46</td>\n",
       "      <td>93.16</td>\n",
       "      <td>5.55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>California</td>\n",
       "      <td>39536653.0</td>\n",
       "      <td>33.73</td>\n",
       "      <td>85.81</td>\n",
       "      <td>5.87</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Colorado</td>\n",
       "      <td>5607154.0</td>\n",
       "      <td>41.44</td>\n",
       "      <td>96.12</td>\n",
       "      <td>4.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Connecticut</td>\n",
       "      <td>3588184.0</td>\n",
       "      <td>38.76</td>\n",
       "      <td>93.70</td>\n",
       "      <td>6.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Delaware</td>\n",
       "      <td>961939.0</td>\n",
       "      <td>31.59</td>\n",
       "      <td>94.17</td>\n",
       "      <td>5.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>District of Columbia</td>\n",
       "      <td>693972.0</td>\n",
       "      <td>57.60</td>\n",
       "      <td>93.24</td>\n",
       "      <td>6.54</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Florida</td>\n",
       "      <td>20984400.0</td>\n",
       "      <td>29.72</td>\n",
       "      <td>92.71</td>\n",
       "      <td>5.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Georgia</td>\n",
       "      <td>10429379.0</td>\n",
       "      <td>31.04</td>\n",
       "      <td>92.20</td>\n",
       "      <td>5.71</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Hawaii</td>\n",
       "      <td>1427538.0</td>\n",
       "      <td>33.87</td>\n",
       "      <td>97.16</td>\n",
       "      <td>3.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Idaho</td>\n",
       "      <td>1716943.0</td>\n",
       "      <td>26.83</td>\n",
       "      <td>96.89</td>\n",
       "      <td>4.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Illinois</td>\n",
       "      <td>12802023.0</td>\n",
       "      <td>34.47</td>\n",
       "      <td>92.83</td>\n",
       "      <td>6.13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Indiana</td>\n",
       "      <td>6666818.0</td>\n",
       "      <td>26.84</td>\n",
       "      <td>93.97</td>\n",
       "      <td>4.74</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Iowa</td>\n",
       "      <td>3145711.0</td>\n",
       "      <td>28.95</td>\n",
       "      <td>96.18</td>\n",
       "      <td>3.58</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Kansas</td>\n",
       "      <td>2913123.0</td>\n",
       "      <td>33.92</td>\n",
       "      <td>95.30</td>\n",
       "      <td>4.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Kentucky</td>\n",
       "      <td>4454189.0</td>\n",
       "      <td>24.03</td>\n",
       "      <td>93.30</td>\n",
       "      <td>5.47</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Louisiana</td>\n",
       "      <td>4684333.0</td>\n",
       "      <td>23.87</td>\n",
       "      <td>90.68</td>\n",
       "      <td>6.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Maine</td>\n",
       "      <td>1335907.0</td>\n",
       "      <td>32.10</td>\n",
       "      <td>97.36</td>\n",
       "      <td>4.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Maryland</td>\n",
       "      <td>6052177.0</td>\n",
       "      <td>39.84</td>\n",
       "      <td>93.45</td>\n",
       "      <td>5.17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Massachusetts</td>\n",
       "      <td>6859819.0</td>\n",
       "      <td>43.44</td>\n",
       "      <td>93.55</td>\n",
       "      <td>4.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Michigan</td>\n",
       "      <td>9962311.0</td>\n",
       "      <td>29.13</td>\n",
       "      <td>94.83</td>\n",
       "      <td>5.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Minnesota</td>\n",
       "      <td>5576606.0</td>\n",
       "      <td>36.07</td>\n",
       "      <td>96.23</td>\n",
       "      <td>3.60</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Mississippi</td>\n",
       "      <td>2984100.0</td>\n",
       "      <td>21.93</td>\n",
       "      <td>90.83</td>\n",
       "      <td>6.97</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Missouri</td>\n",
       "      <td>6113532.0</td>\n",
       "      <td>29.11</td>\n",
       "      <td>94.50</td>\n",
       "      <td>4.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Montana</td>\n",
       "      <td>1050493.0</td>\n",
       "      <td>32.37</td>\n",
       "      <td>97.75</td>\n",
       "      <td>3.49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Nebraska</td>\n",
       "      <td>1920076.0</td>\n",
       "      <td>31.77</td>\n",
       "      <td>95.11</td>\n",
       "      <td>3.33</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Nevada</td>\n",
       "      <td>2998039.0</td>\n",
       "      <td>24.96</td>\n",
       "      <td>90.99</td>\n",
       "      <td>5.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>New Hampshire</td>\n",
       "      <td>1342795.0</td>\n",
       "      <td>36.98</td>\n",
       "      <td>97.49</td>\n",
       "      <td>3.80</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>New Jersey</td>\n",
       "      <td>9005644.0</td>\n",
       "      <td>39.77</td>\n",
       "      <td>92.49</td>\n",
       "      <td>5.32</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>New Mexico</td>\n",
       "      <td>2088070.0</td>\n",
       "      <td>27.16</td>\n",
       "      <td>91.01</td>\n",
       "      <td>6.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>New York</td>\n",
       "      <td>19849399.0</td>\n",
       "      <td>36.07</td>\n",
       "      <td>90.70</td>\n",
       "      <td>5.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>North Carolina</td>\n",
       "      <td>10273419.0</td>\n",
       "      <td>31.55</td>\n",
       "      <td>92.60</td>\n",
       "      <td>5.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>North Dakota</td>\n",
       "      <td>755393.0</td>\n",
       "      <td>31.00</td>\n",
       "      <td>97.75</td>\n",
       "      <td>2.89</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Ohio</td>\n",
       "      <td>11658609.0</td>\n",
       "      <td>27.98</td>\n",
       "      <td>94.24</td>\n",
       "      <td>5.15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Oklahoma</td>\n",
       "      <td>3930864.0</td>\n",
       "      <td>25.63</td>\n",
       "      <td>93.29</td>\n",
       "      <td>5.31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Oregon</td>\n",
       "      <td>4142776.0</td>\n",
       "      <td>33.75</td>\n",
       "      <td>95.38</td>\n",
       "      <td>5.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>Pennsylvania</td>\n",
       "      <td>12805537.0</td>\n",
       "      <td>31.46</td>\n",
       "      <td>94.48</td>\n",
       "      <td>5.29</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>Rhode Island</td>\n",
       "      <td>1059639.0</td>\n",
       "      <td>33.56</td>\n",
       "      <td>93.37</td>\n",
       "      <td>5.70</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>South Carolina</td>\n",
       "      <td>5024369.0</td>\n",
       "      <td>28.12</td>\n",
       "      <td>92.25</td>\n",
       "      <td>5.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>South Dakota</td>\n",
       "      <td>869666.0</td>\n",
       "      <td>28.23</td>\n",
       "      <td>96.28</td>\n",
       "      <td>3.51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>Tennessee</td>\n",
       "      <td>6715984.0</td>\n",
       "      <td>27.42</td>\n",
       "      <td>93.92</td>\n",
       "      <td>4.90</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>Texas</td>\n",
       "      <td>28304596.0</td>\n",
       "      <td>29.67</td>\n",
       "      <td>88.21</td>\n",
       "      <td>5.12</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>Utah</td>\n",
       "      <td>3101833.0</td>\n",
       "      <td>34.67</td>\n",
       "      <td>95.25</td>\n",
       "      <td>3.56</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>Vermont</td>\n",
       "      <td>623657.0</td>\n",
       "      <td>38.33</td>\n",
       "      <td>95.95</td>\n",
       "      <td>3.76</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>Virginia</td>\n",
       "      <td>8470020.0</td>\n",
       "      <td>39.23</td>\n",
       "      <td>94.86</td>\n",
       "      <td>4.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>Washington</td>\n",
       "      <td>7405743.0</td>\n",
       "      <td>35.70</td>\n",
       "      <td>95.54</td>\n",
       "      <td>4.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>West Virginia</td>\n",
       "      <td>1815857.0</td>\n",
       "      <td>20.23</td>\n",
       "      <td>93.73</td>\n",
       "      <td>6.68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>Wisconsin</td>\n",
       "      <td>5795483.0</td>\n",
       "      <td>30.40</td>\n",
       "      <td>95.90</td>\n",
       "      <td>3.48</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>Wyoming</td>\n",
       "      <td>579315.0</td>\n",
       "      <td>27.79</td>\n",
       "      <td>98.89</td>\n",
       "      <td>5.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>Puerto Rico</td>\n",
       "      <td>3337177.0</td>\n",
       "      <td>25.73</td>\n",
       "      <td>78.76</td>\n",
       "      <td>16.38</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   State  Population  Bachelors Rate  HS Diploma Rate  \\\n",
       "0                Alabama   4874747.0           25.60            92.22   \n",
       "1                 Alaska    739795.0           29.35            99.27   \n",
       "2                Arizona   7016270.0           29.43            91.37   \n",
       "3               Arkansas   3004279.0           23.46            93.16   \n",
       "4             California  39536653.0           33.73            85.81   \n",
       "5               Colorado   5607154.0           41.44            96.12   \n",
       "6            Connecticut   3588184.0           38.76            93.70   \n",
       "7               Delaware    961939.0           31.59            94.17   \n",
       "8   District of Columbia    693972.0           57.60            93.24   \n",
       "9                Florida  20984400.0           29.72            92.71   \n",
       "10               Georgia  10429379.0           31.04            92.20   \n",
       "11                Hawaii   1427538.0           33.87            97.16   \n",
       "12                 Idaho   1716943.0           26.83            96.89   \n",
       "13              Illinois  12802023.0           34.47            92.83   \n",
       "14               Indiana   6666818.0           26.84            93.97   \n",
       "15                  Iowa   3145711.0           28.95            96.18   \n",
       "16                Kansas   2913123.0           33.92            95.30   \n",
       "17              Kentucky   4454189.0           24.03            93.30   \n",
       "18             Louisiana   4684333.0           23.87            90.68   \n",
       "19                 Maine   1335907.0           32.10            97.36   \n",
       "20              Maryland   6052177.0           39.84            93.45   \n",
       "21         Massachusetts   6859819.0           43.44            93.55   \n",
       "22              Michigan   9962311.0           29.13            94.83   \n",
       "23             Minnesota   5576606.0           36.07            96.23   \n",
       "24           Mississippi   2984100.0           21.93            90.83   \n",
       "25              Missouri   6113532.0           29.11            94.50   \n",
       "26               Montana   1050493.0           32.37            97.75   \n",
       "27              Nebraska   1920076.0           31.77            95.11   \n",
       "28                Nevada   2998039.0           24.96            90.99   \n",
       "29         New Hampshire   1342795.0           36.98            97.49   \n",
       "30            New Jersey   9005644.0           39.77            92.49   \n",
       "31            New Mexico   2088070.0           27.16            91.01   \n",
       "32              New York  19849399.0           36.07            90.70   \n",
       "33        North Carolina  10273419.0           31.55            92.60   \n",
       "34          North Dakota    755393.0           31.00            97.75   \n",
       "35                  Ohio  11658609.0           27.98            94.24   \n",
       "36              Oklahoma   3930864.0           25.63            93.29   \n",
       "37                Oregon   4142776.0           33.75            95.38   \n",
       "38          Pennsylvania  12805537.0           31.46            94.48   \n",
       "39          Rhode Island   1059639.0           33.56            93.37   \n",
       "40        South Carolina   5024369.0           28.12            92.25   \n",
       "41          South Dakota    869666.0           28.23            96.28   \n",
       "42             Tennessee   6715984.0           27.42            93.92   \n",
       "43                 Texas  28304596.0           29.67            88.21   \n",
       "44                  Utah   3101833.0           34.67            95.25   \n",
       "45               Vermont    623657.0           38.33            95.95   \n",
       "46              Virginia   8470020.0           39.23            94.86   \n",
       "47            Washington   7405743.0           35.70            95.54   \n",
       "48         West Virginia   1815857.0           20.23            93.73   \n",
       "49             Wisconsin   5795483.0           30.40            95.90   \n",
       "50               Wyoming    579315.0           27.79            98.89   \n",
       "51           Puerto Rico   3337177.0           25.73            78.76   \n",
       "\n",
       "    Unemployment Rate  \n",
       "0                5.81  \n",
       "1                7.25  \n",
       "2                5.77  \n",
       "3                5.55  \n",
       "4                5.87  \n",
       "5                4.16  \n",
       "6                6.08  \n",
       "7                5.24  \n",
       "8                6.54  \n",
       "9                5.47  \n",
       "10               5.71  \n",
       "11               3.95  \n",
       "12               4.12  \n",
       "13               6.13  \n",
       "14               4.74  \n",
       "15               3.58  \n",
       "16               4.16  \n",
       "17               5.47  \n",
       "18               6.50  \n",
       "19               4.20  \n",
       "20               5.17  \n",
       "21               4.56  \n",
       "22               5.88  \n",
       "23               3.60  \n",
       "24               6.97  \n",
       "25               4.59  \n",
       "26               3.49  \n",
       "27               3.33  \n",
       "28               5.91  \n",
       "29               3.80  \n",
       "30               5.32  \n",
       "31               6.50  \n",
       "32               5.48  \n",
       "33               5.19  \n",
       "34               2.89  \n",
       "35               5.15  \n",
       "36               5.31  \n",
       "37               5.09  \n",
       "38               5.29  \n",
       "39               5.70  \n",
       "40               5.72  \n",
       "41               3.51  \n",
       "42               4.90  \n",
       "43               5.12  \n",
       "44               3.56  \n",
       "45               3.76  \n",
       "46               4.48  \n",
       "47               4.86  \n",
       "48               6.68  \n",
       "49               3.48  \n",
       "50               5.11  \n",
       "51              16.38  "
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Pull US Census Data for each State\n",
    "census_data = c.acs1.get((\"NAME\", \"B01003_001E\", \"B15003_022E\",\"B15003_023E\",\"B15003_024E\",\"B15003_025E\",\n",
    "                          \"B23025_002E\",\"B23025_005E\", \"B21003_001E\", \"B15003_017E\",\"B15003_018E\",\"B15003_019E\",\n",
    "                         \"B15003_020E\",\"B15003_021E\", \"B19013_001E\"), {'for': 'state:*'})\n",
    "census_2017 = pd.DataFrame(census_data)\n",
    "\n",
    "\n",
    "# B15003_022E = Bachelors Degree\n",
    "# B15003_023E = Masters\n",
    "# B15003_024E = Professional\n",
    "# B15003_025E = Doctor\n",
    "# B19013_001E = Household income\n",
    "# B01003_001E = Population\n",
    "# B01002_001E = Median Age\n",
    "# B19301_001E = Per Capita Income\n",
    "# B15003_023E = Masters Degree\n",
    "# B23025_002E = Labor Force\n",
    "# B23025_004E = Employed\n",
    "# B23025_005E = Unemployed\n",
    "# B25077_001E = Median Home Value\n",
    "# B08136_003E = Commute Time (in minutes)\n",
    "# B19013_001E = Median Income\n",
    "\n",
    "\n",
    "census_2017 = census_2017.rename(columns={\"B01003_001E\": \"Population\",\n",
    "                                      \"B15003_022E\": \"Bachelors\",\n",
    "                                      \"B15003_023E\": \"Masters\",\n",
    "                                      \"B15003_024E\": \"Professional\",\n",
    "                                      \"B15003_025E\": \"Doctor\",\n",
    "                                      \"B23025_002E\": \"Labor Force\",\n",
    "                                      \"B23025_005E\": \"Unemployed\",\n",
    "                                      \"B21003_001E\": \"Pop25\",\n",
    "                                      \"B15003_017E\": \"HS\",\n",
    "                                      \"B15003_018E\": \"GED\",\n",
    "                                      \"B15003_019E\": \"Under 1\",\n",
    "                                      \"B15003_020E\": \"Over 1\",\n",
    "                                      \"B15003_021E\": \"Associates\",\n",
    "                                      \"NAME\": \"State\", \"state\": \"Code\"})\n",
    "\n",
    "# Add dataframe columns for bachelors and above as well as HS diploma and above (including GED)\n",
    "census_2017[\"Bachelor+\"] = census_2017[\"Bachelors\"]+census_2017[\"Masters\"]+census_2017[\"Professional\"]+census_2017[\"Doctor\"]\n",
    "census_2017[\"HS+\"]= census_2017[\"HS\"]+census_2017[\"GED\"]+census_2017[\"Bachelor+\"]+census_2017[\"Under 1\"]+census_2017[\"Over 1\"]+census_2017[\"Associates\"]\n",
    "\n",
    "census_2017 = census_2017[[\"State\", \"Population\",\"Pop25\", \"HS\",\"GED\",\"HS+\",\"Bachelors\", \"Bachelor+\",\"Labor Force\", \"Unemployed\"]]\n",
    "\n",
    "census_2017[\"Bachelors Rate\"] = round((census_2017[\"Bachelor+\"]/census_2017[\"Pop25\"])*100,2)\n",
    "census_2017[\"HS Diploma Rate\"] = round(((census_2017[\"HS+\"] + census_2017[\"GED\"])/census_2017[\"Pop25\"])*100,2)\n",
    "census_2017[\"Unemployment Rate\"] = round((census_2017[\"Unemployed\"]/census_2017[\"Labor Force\"])*100,2)\n",
    "\n",
    "# Final Dataframe\n",
    "census_2017 = census_2017[[\"State\", \"Population\",\"Bachelors Rate\", \"HS Diploma Rate\",\"Unemployment Rate\"]]\n",
    "# census_2017.to_csv(\"output.csv\")\n",
    "\n",
    "\n",
    "\n",
    "census_2017"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>State</th>\n",
       "      <th>Population</th>\n",
       "      <th>Bachelors Rate</th>\n",
       "      <th>HS Diploma Rate</th>\n",
       "      <th>Unemployment Rate</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Alabama</td>\n",
       "      <td>4802740.0</td>\n",
       "      <td>22.33</td>\n",
       "      <td>88.27</td>\n",
       "      <td>11.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Alaska</td>\n",
       "      <td>722718.0</td>\n",
       "      <td>26.96</td>\n",
       "      <td>99.11</td>\n",
       "      <td>8.46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Arizona</td>\n",
       "      <td>6482505.0</td>\n",
       "      <td>26.64</td>\n",
       "      <td>89.86</td>\n",
       "      <td>11.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Arkansas</td>\n",
       "      <td>2937979.0</td>\n",
       "      <td>20.35</td>\n",
       "      <td>89.93</td>\n",
       "      <td>9.31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>California</td>\n",
       "      <td>37691912.0</td>\n",
       "      <td>30.39</td>\n",
       "      <td>83.53</td>\n",
       "      <td>12.25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Colorado</td>\n",
       "      <td>5116796.0</td>\n",
       "      <td>36.88</td>\n",
       "      <td>94.53</td>\n",
       "      <td>9.19</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Connecticut</td>\n",
       "      <td>3580709.0</td>\n",
       "      <td>36.23</td>\n",
       "      <td>92.47</td>\n",
       "      <td>10.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Delaware</td>\n",
       "      <td>907135.0</td>\n",
       "      <td>28.95</td>\n",
       "      <td>90.49</td>\n",
       "      <td>8.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>District of Columbia</td>\n",
       "      <td>617996.0</td>\n",
       "      <td>52.61</td>\n",
       "      <td>90.06</td>\n",
       "      <td>11.31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Florida</td>\n",
       "      <td>19057542.0</td>\n",
       "      <td>25.91</td>\n",
       "      <td>90.30</td>\n",
       "      <td>12.34</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Georgia</td>\n",
       "      <td>9815210.0</td>\n",
       "      <td>27.68</td>\n",
       "      <td>89.42</td>\n",
       "      <td>12.04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Hawaii</td>\n",
       "      <td>1374810.0</td>\n",
       "      <td>29.82</td>\n",
       "      <td>95.28</td>\n",
       "      <td>7.28</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Idaho</td>\n",
       "      <td>1584985.0</td>\n",
       "      <td>25.29</td>\n",
       "      <td>93.83</td>\n",
       "      <td>9.94</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Illinois</td>\n",
       "      <td>12869259.0</td>\n",
       "      <td>31.06</td>\n",
       "      <td>90.78</td>\n",
       "      <td>10.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Indiana</td>\n",
       "      <td>6516922.0</td>\n",
       "      <td>23.03</td>\n",
       "      <td>92.24</td>\n",
       "      <td>9.99</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Iowa</td>\n",
       "      <td>3062309.0</td>\n",
       "      <td>25.82</td>\n",
       "      <td>94.69</td>\n",
       "      <td>6.02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Kansas</td>\n",
       "      <td>2871238.0</td>\n",
       "      <td>30.31</td>\n",
       "      <td>95.18</td>\n",
       "      <td>7.36</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Kentucky</td>\n",
       "      <td>4369356.0</td>\n",
       "      <td>21.14</td>\n",
       "      <td>90.56</td>\n",
       "      <td>10.34</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Louisiana</td>\n",
       "      <td>4574836.0</td>\n",
       "      <td>21.18</td>\n",
       "      <td>88.13</td>\n",
       "      <td>9.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Maine</td>\n",
       "      <td>1328188.0</td>\n",
       "      <td>28.43</td>\n",
       "      <td>95.99</td>\n",
       "      <td>8.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Maryland</td>\n",
       "      <td>5828289.0</td>\n",
       "      <td>37.04</td>\n",
       "      <td>92.03</td>\n",
       "      <td>8.83</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Massachusetts</td>\n",
       "      <td>6587536.0</td>\n",
       "      <td>39.19</td>\n",
       "      <td>92.18</td>\n",
       "      <td>9.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Michigan</td>\n",
       "      <td>9876187.0</td>\n",
       "      <td>25.64</td>\n",
       "      <td>92.81</td>\n",
       "      <td>13.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Minnesota</td>\n",
       "      <td>5344861.0</td>\n",
       "      <td>32.39</td>\n",
       "      <td>95.12</td>\n",
       "      <td>7.65</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Mississippi</td>\n",
       "      <td>2978512.0</td>\n",
       "      <td>19.91</td>\n",
       "      <td>87.01</td>\n",
       "      <td>11.25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Missouri</td>\n",
       "      <td>6010688.0</td>\n",
       "      <td>26.13</td>\n",
       "      <td>92.29</td>\n",
       "      <td>9.35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Montana</td>\n",
       "      <td>998199.0</td>\n",
       "      <td>28.27</td>\n",
       "      <td>97.66</td>\n",
       "      <td>7.88</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Nebraska</td>\n",
       "      <td>1842641.0</td>\n",
       "      <td>28.01</td>\n",
       "      <td>94.51</td>\n",
       "      <td>6.25</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Nevada</td>\n",
       "      <td>2723322.0</td>\n",
       "      <td>22.56</td>\n",
       "      <td>88.31</td>\n",
       "      <td>12.57</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>New Hampshire</td>\n",
       "      <td>1318194.0</td>\n",
       "      <td>33.42</td>\n",
       "      <td>95.22</td>\n",
       "      <td>6.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>New Jersey</td>\n",
       "      <td>8821155.0</td>\n",
       "      <td>35.32</td>\n",
       "      <td>90.77</td>\n",
       "      <td>10.92</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>New Mexico</td>\n",
       "      <td>2082224.0</td>\n",
       "      <td>25.65</td>\n",
       "      <td>87.74</td>\n",
       "      <td>11.09</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>New York</td>\n",
       "      <td>19465197.0</td>\n",
       "      <td>32.96</td>\n",
       "      <td>88.80</td>\n",
       "      <td>9.55</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>North Carolina</td>\n",
       "      <td>9656401.0</td>\n",
       "      <td>27.12</td>\n",
       "      <td>89.61</td>\n",
       "      <td>11.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>North Dakota</td>\n",
       "      <td>683932.0</td>\n",
       "      <td>26.42</td>\n",
       "      <td>94.55</td>\n",
       "      <td>3.10</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Ohio</td>\n",
       "      <td>11544951.0</td>\n",
       "      <td>24.68</td>\n",
       "      <td>92.15</td>\n",
       "      <td>10.41</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Oklahoma</td>\n",
       "      <td>3791508.0</td>\n",
       "      <td>23.92</td>\n",
       "      <td>91.52</td>\n",
       "      <td>7.46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Oregon</td>\n",
       "      <td>3871859.0</td>\n",
       "      <td>29.35</td>\n",
       "      <td>93.82</td>\n",
       "      <td>11.96</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>Pennsylvania</td>\n",
       "      <td>12742886.0</td>\n",
       "      <td>26.98</td>\n",
       "      <td>92.67</td>\n",
       "      <td>9.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>Rhode Island</td>\n",
       "      <td>1051302.0</td>\n",
       "      <td>31.25</td>\n",
       "      <td>89.52</td>\n",
       "      <td>10.23</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>South Carolina</td>\n",
       "      <td>4679230.0</td>\n",
       "      <td>24.20</td>\n",
       "      <td>88.81</td>\n",
       "      <td>11.74</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>South Dakota</td>\n",
       "      <td>824082.0</td>\n",
       "      <td>26.48</td>\n",
       "      <td>95.87</td>\n",
       "      <td>5.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>Tennessee</td>\n",
       "      <td>6403353.0</td>\n",
       "      <td>23.68</td>\n",
       "      <td>90.57</td>\n",
       "      <td>10.50</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>Texas</td>\n",
       "      <td>25674681.0</td>\n",
       "      <td>26.53</td>\n",
       "      <td>85.93</td>\n",
       "      <td>8.44</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>Utah</td>\n",
       "      <td>2817222.0</td>\n",
       "      <td>29.81</td>\n",
       "      <td>93.12</td>\n",
       "      <td>7.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>Vermont</td>\n",
       "      <td>626431.0</td>\n",
       "      <td>35.46</td>\n",
       "      <td>95.36</td>\n",
       "      <td>6.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>Virginia</td>\n",
       "      <td>8096604.0</td>\n",
       "      <td>35.59</td>\n",
       "      <td>92.98</td>\n",
       "      <td>7.37</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>Washington</td>\n",
       "      <td>6830038.0</td>\n",
       "      <td>32.12</td>\n",
       "      <td>94.72</td>\n",
       "      <td>10.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>West Virginia</td>\n",
       "      <td>1855364.0</td>\n",
       "      <td>18.48</td>\n",
       "      <td>90.81</td>\n",
       "      <td>8.86</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>Wisconsin</td>\n",
       "      <td>5711767.0</td>\n",
       "      <td>26.50</td>\n",
       "      <td>93.94</td>\n",
       "      <td>8.16</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>Wyoming</td>\n",
       "      <td>568158.0</td>\n",
       "      <td>24.81</td>\n",
       "      <td>97.83</td>\n",
       "      <td>5.05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>Puerto Rico</td>\n",
       "      <td>3706690.0</td>\n",
       "      <td>23.32</td>\n",
       "      <td>74.23</td>\n",
       "      <td>18.46</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   State  Population  Bachelors Rate  HS Diploma Rate  \\\n",
       "0                Alabama   4802740.0           22.33            88.27   \n",
       "1                 Alaska    722718.0           26.96            99.11   \n",
       "2                Arizona   6482505.0           26.64            89.86   \n",
       "3               Arkansas   2937979.0           20.35            89.93   \n",
       "4             California  37691912.0           30.39            83.53   \n",
       "5               Colorado   5116796.0           36.88            94.53   \n",
       "6            Connecticut   3580709.0           36.23            92.47   \n",
       "7               Delaware    907135.0           28.95            90.49   \n",
       "8   District of Columbia    617996.0           52.61            90.06   \n",
       "9                Florida  19057542.0           25.91            90.30   \n",
       "10               Georgia   9815210.0           27.68            89.42   \n",
       "11                Hawaii   1374810.0           29.82            95.28   \n",
       "12                 Idaho   1584985.0           25.29            93.83   \n",
       "13              Illinois  12869259.0           31.06            90.78   \n",
       "14               Indiana   6516922.0           23.03            92.24   \n",
       "15                  Iowa   3062309.0           25.82            94.69   \n",
       "16                Kansas   2871238.0           30.31            95.18   \n",
       "17              Kentucky   4369356.0           21.14            90.56   \n",
       "18             Louisiana   4574836.0           21.18            88.13   \n",
       "19                 Maine   1328188.0           28.43            95.99   \n",
       "20              Maryland   5828289.0           37.04            92.03   \n",
       "21         Massachusetts   6587536.0           39.19            92.18   \n",
       "22              Michigan   9876187.0           25.64            92.81   \n",
       "23             Minnesota   5344861.0           32.39            95.12   \n",
       "24           Mississippi   2978512.0           19.91            87.01   \n",
       "25              Missouri   6010688.0           26.13            92.29   \n",
       "26               Montana    998199.0           28.27            97.66   \n",
       "27              Nebraska   1842641.0           28.01            94.51   \n",
       "28                Nevada   2723322.0           22.56            88.31   \n",
       "29         New Hampshire   1318194.0           33.42            95.22   \n",
       "30            New Jersey   8821155.0           35.32            90.77   \n",
       "31            New Mexico   2082224.0           25.65            87.74   \n",
       "32              New York  19465197.0           32.96            88.80   \n",
       "33        North Carolina   9656401.0           27.12            89.61   \n",
       "34          North Dakota    683932.0           26.42            94.55   \n",
       "35                  Ohio  11544951.0           24.68            92.15   \n",
       "36              Oklahoma   3791508.0           23.92            91.52   \n",
       "37                Oregon   3871859.0           29.35            93.82   \n",
       "38          Pennsylvania  12742886.0           26.98            92.67   \n",
       "39          Rhode Island   1051302.0           31.25            89.52   \n",
       "40        South Carolina   4679230.0           24.20            88.81   \n",
       "41          South Dakota    824082.0           26.48            95.87   \n",
       "42             Tennessee   6403353.0           23.68            90.57   \n",
       "43                 Texas  25674681.0           26.53            85.93   \n",
       "44                  Utah   2817222.0           29.81            93.12   \n",
       "45               Vermont    626431.0           35.46            95.36   \n",
       "46              Virginia   8096604.0           35.59            92.98   \n",
       "47            Washington   6830038.0           32.12            94.72   \n",
       "48         West Virginia   1855364.0           18.48            90.81   \n",
       "49             Wisconsin   5711767.0           26.50            93.94   \n",
       "50               Wyoming    568158.0           24.81            97.83   \n",
       "51           Puerto Rico   3706690.0           23.32            74.23   \n",
       "\n",
       "    Unemployment Rate  \n",
       "0               11.50  \n",
       "1                8.46  \n",
       "2               11.09  \n",
       "3                9.31  \n",
       "4               12.25  \n",
       "5                9.19  \n",
       "6               10.57  \n",
       "7                8.88  \n",
       "8               11.31  \n",
       "9               12.34  \n",
       "10              12.04  \n",
       "11               7.28  \n",
       "12               9.94  \n",
       "13              10.99  \n",
       "14               9.99  \n",
       "15               6.02  \n",
       "16               7.36  \n",
       "17              10.34  \n",
       "18               9.20  \n",
       "19               8.57  \n",
       "20               8.83  \n",
       "21               9.24  \n",
       "22              13.05  \n",
       "23               7.65  \n",
       "24              11.25  \n",
       "25               9.35  \n",
       "26               7.88  \n",
       "27               6.25  \n",
       "28              12.57  \n",
       "29               6.86  \n",
       "30              10.92  \n",
       "31              11.09  \n",
       "32               9.55  \n",
       "33              11.50  \n",
       "34               3.10  \n",
       "35              10.41  \n",
       "36               7.46  \n",
       "37              11.96  \n",
       "38               9.37  \n",
       "39              10.23  \n",
       "40              11.74  \n",
       "41               5.44  \n",
       "42              10.50  \n",
       "43               8.44  \n",
       "44               7.95  \n",
       "45               6.40  \n",
       "46               7.37  \n",
       "47              10.18  \n",
       "48               8.86  \n",
       "49               8.16  \n",
       "50               5.05  \n",
       "51              18.46  "
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Build exact same dataframe for 2011 data\n",
    "census_data2 = c2.acs1.get((\"NAME\", \"B01003_001E\", \"B15003_022E\",\"B15003_023E\",\"B15003_024E\",\"B15003_025E\",\n",
    "                          \"B23025_002E\",\"B23025_005E\", \"B21003_001E\", \"B15003_017E\",\"B15003_018E\",\"B15003_019E\",\n",
    "                         \"B15003_020E\",\"B15003_021E\",\"B19013_001E\"), {'for': 'state:*'})\n",
    "census_2011 = pd.DataFrame(census_data2)\n",
    "\n",
    "census_2011 = census_2011.rename(columns={\"B01003_001E\": \"Population\",\n",
    "                                      \"B15003_022E\": \"Bachelors\",\n",
    "                                      \"B15003_023E\": \"Masters\",\n",
    "                                      \"B15003_024E\": \"Professional\",\n",
    "                                      \"B15003_025E\": \"Doctor\",\n",
    "                                      \"B23025_002E\": \"Labor Force\",\n",
    "                                      \"B23025_005E\": \"Unemployed\",\n",
    "                                      \"B21003_001E\": \"Pop25\",\n",
    "                                      \"B15003_017E\": \"HS\",\n",
    "                                      \"B15003_018E\": \"GED\",\n",
    "                                      \"B15003_019E\": \"Under 1\",\n",
    "                                      \"B15003_020E\": \"Over 1\",\n",
    "                                      \"B15003_021E\": \"Associates\",\n",
    "                                      \"NAME\": \"State\", \"state\": \"Code\"})\n",
    "\n",
    "census_2011[\"Bachelor+\"] = census_2011[\"Bachelors\"]+census_2011[\"Masters\"]+census_2011[\"Professional\"]+census_2011[\"Doctor\"]\n",
    "census_2011[\"HS+\"]= census_2011[\"HS\"]+census_2011[\"GED\"]+census_2011[\"Bachelor+\"]+census_2011[\"Under 1\"]+census_2011[\"Over 1\"]+census_2011[\"Associates\"]\n",
    "\n",
    "census_2011 = census_2011[[\"State\", \"Population\",\"Pop25\", \"HS\",\"GED\",\"HS+\",\"Bachelors\", \"Bachelor+\",\"Labor Force\", \"Unemployed\"]]\n",
    "\n",
    "census_2011[\"Bachelors Rate\"] = round((census_2011[\"Bachelor+\"]/census_2011[\"Pop25\"])*100,2)\n",
    "census_2011[\"HS Diploma Rate\"] = round(((census_2011[\"HS+\"] + census_2011[\"GED\"])/census_2011[\"Pop25\"])*100,2)\n",
    "census_2011[\"Unemployment Rate\"] = round((census_2011[\"Unemployed\"]/census_2011[\"Labor Force\"])*100,2)\n",
    "\n",
    "census_2011 = census_2011[[\"State\", \"Population\",\"Bachelors Rate\", \"HS Diploma Rate\",\"Unemployment Rate\"]]\n",
    "\n",
    "census_2011"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>State</th>\n",
       "      <th>Population Change</th>\n",
       "      <th>Population Score</th>\n",
       "      <th>Education Change</th>\n",
       "      <th>Education Score</th>\n",
       "      <th>Unemployment Change</th>\n",
       "      <th>Unemployment Score</th>\n",
       "      <th>Composite Score</th>\n",
       "      <th>Composite Rank</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Alabama</td>\n",
       "      <td>1.50</td>\n",
       "      <td>14.0</td>\n",
       "      <td>14.64</td>\n",
       "      <td>40.0</td>\n",
       "      <td>-49.48</td>\n",
       "      <td>29.0</td>\n",
       "      <td>83.0</td>\n",
       "      <td>24.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Alaska</td>\n",
       "      <td>2.36</td>\n",
       "      <td>23.0</td>\n",
       "      <td>8.86</td>\n",
       "      <td>9.0</td>\n",
       "      <td>-14.30</td>\n",
       "      <td>3.0</td>\n",
       "      <td>35.0</td>\n",
       "      <td>46.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Arizona</td>\n",
       "      <td>8.23</td>\n",
       "      <td>42.0</td>\n",
       "      <td>10.47</td>\n",
       "      <td>16.0</td>\n",
       "      <td>-47.97</td>\n",
       "      <td>28.0</td>\n",
       "      <td>86.0</td>\n",
       "      <td>21.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Arkansas</td>\n",
       "      <td>2.26</td>\n",
       "      <td>21.0</td>\n",
       "      <td>15.28</td>\n",
       "      <td>44.0</td>\n",
       "      <td>-40.39</td>\n",
       "      <td>11.0</td>\n",
       "      <td>76.0</td>\n",
       "      <td>29.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>California</td>\n",
       "      <td>4.89</td>\n",
       "      <td>34.0</td>\n",
       "      <td>10.99</td>\n",
       "      <td>21.0</td>\n",
       "      <td>-52.08</td>\n",
       "      <td>36.0</td>\n",
       "      <td>91.0</td>\n",
       "      <td>18.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Colorado</td>\n",
       "      <td>9.58</td>\n",
       "      <td>45.0</td>\n",
       "      <td>12.36</td>\n",
       "      <td>30.0</td>\n",
       "      <td>-54.73</td>\n",
       "      <td>43.0</td>\n",
       "      <td>118.0</td>\n",
       "      <td>8.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Connecticut</td>\n",
       "      <td>0.21</td>\n",
       "      <td>5.0</td>\n",
       "      <td>6.98</td>\n",
       "      <td>4.0</td>\n",
       "      <td>-42.48</td>\n",
       "      <td>18.0</td>\n",
       "      <td>27.0</td>\n",
       "      <td>47.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Delaware</td>\n",
       "      <td>6.04</td>\n",
       "      <td>37.0</td>\n",
       "      <td>9.12</td>\n",
       "      <td>10.0</td>\n",
       "      <td>-40.99</td>\n",
       "      <td>13.0</td>\n",
       "      <td>60.0</td>\n",
       "      <td>35.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>District of Columbia</td>\n",
       "      <td>12.29</td>\n",
       "      <td>51.0</td>\n",
       "      <td>9.48</td>\n",
       "      <td>13.0</td>\n",
       "      <td>-42.18</td>\n",
       "      <td>17.0</td>\n",
       "      <td>81.0</td>\n",
       "      <td>26.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Florida</td>\n",
       "      <td>10.11</td>\n",
       "      <td>48.0</td>\n",
       "      <td>14.70</td>\n",
       "      <td>41.0</td>\n",
       "      <td>-55.67</td>\n",
       "      <td>47.0</td>\n",
       "      <td>136.0</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Georgia</td>\n",
       "      <td>6.26</td>\n",
       "      <td>38.0</td>\n",
       "      <td>12.14</td>\n",
       "      <td>29.0</td>\n",
       "      <td>-52.57</td>\n",
       "      <td>39.0</td>\n",
       "      <td>106.0</td>\n",
       "      <td>10.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Hawaii</td>\n",
       "      <td>3.84</td>\n",
       "      <td>27.5</td>\n",
       "      <td>13.58</td>\n",
       "      <td>36.0</td>\n",
       "      <td>-45.74</td>\n",
       "      <td>25.0</td>\n",
       "      <td>88.5</td>\n",
       "      <td>20.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Idaho</td>\n",
       "      <td>8.33</td>\n",
       "      <td>43.0</td>\n",
       "      <td>6.09</td>\n",
       "      <td>2.0</td>\n",
       "      <td>-58.55</td>\n",
       "      <td>51.0</td>\n",
       "      <td>96.0</td>\n",
       "      <td>15.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Illinois</td>\n",
       "      <td>-0.52</td>\n",
       "      <td>2.0</td>\n",
       "      <td>10.98</td>\n",
       "      <td>20.0</td>\n",
       "      <td>-44.22</td>\n",
       "      <td>22.0</td>\n",
       "      <td>44.0</td>\n",
       "      <td>43.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Indiana</td>\n",
       "      <td>2.30</td>\n",
       "      <td>22.0</td>\n",
       "      <td>16.54</td>\n",
       "      <td>49.0</td>\n",
       "      <td>-52.55</td>\n",
       "      <td>38.0</td>\n",
       "      <td>109.0</td>\n",
       "      <td>9.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>Iowa</td>\n",
       "      <td>2.72</td>\n",
       "      <td>25.0</td>\n",
       "      <td>12.12</td>\n",
       "      <td>28.0</td>\n",
       "      <td>-40.53</td>\n",
       "      <td>12.0</td>\n",
       "      <td>65.0</td>\n",
       "      <td>33.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>Kansas</td>\n",
       "      <td>1.46</td>\n",
       "      <td>12.0</td>\n",
       "      <td>11.91</td>\n",
       "      <td>26.0</td>\n",
       "      <td>-43.48</td>\n",
       "      <td>20.0</td>\n",
       "      <td>58.0</td>\n",
       "      <td>36.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Kentucky</td>\n",
       "      <td>1.94</td>\n",
       "      <td>17.0</td>\n",
       "      <td>13.67</td>\n",
       "      <td>38.0</td>\n",
       "      <td>-47.10</td>\n",
       "      <td>27.0</td>\n",
       "      <td>82.0</td>\n",
       "      <td>25.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>Louisiana</td>\n",
       "      <td>2.39</td>\n",
       "      <td>24.0</td>\n",
       "      <td>12.70</td>\n",
       "      <td>32.0</td>\n",
       "      <td>-29.35</td>\n",
       "      <td>6.0</td>\n",
       "      <td>62.0</td>\n",
       "      <td>34.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Maine</td>\n",
       "      <td>0.58</td>\n",
       "      <td>8.0</td>\n",
       "      <td>12.91</td>\n",
       "      <td>33.0</td>\n",
       "      <td>-50.99</td>\n",
       "      <td>33.0</td>\n",
       "      <td>74.0</td>\n",
       "      <td>31.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>Maryland</td>\n",
       "      <td>3.84</td>\n",
       "      <td>27.5</td>\n",
       "      <td>7.56</td>\n",
       "      <td>7.0</td>\n",
       "      <td>-41.45</td>\n",
       "      <td>16.0</td>\n",
       "      <td>50.5</td>\n",
       "      <td>39.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>Massachusetts</td>\n",
       "      <td>4.13</td>\n",
       "      <td>29.0</td>\n",
       "      <td>10.84</td>\n",
       "      <td>19.0</td>\n",
       "      <td>-50.65</td>\n",
       "      <td>31.0</td>\n",
       "      <td>79.0</td>\n",
       "      <td>27.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>Michigan</td>\n",
       "      <td>0.87</td>\n",
       "      <td>10.0</td>\n",
       "      <td>13.61</td>\n",
       "      <td>37.0</td>\n",
       "      <td>-54.94</td>\n",
       "      <td>45.0</td>\n",
       "      <td>92.0</td>\n",
       "      <td>17.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>Minnesota</td>\n",
       "      <td>4.34</td>\n",
       "      <td>31.0</td>\n",
       "      <td>11.36</td>\n",
       "      <td>23.0</td>\n",
       "      <td>-52.94</td>\n",
       "      <td>40.0</td>\n",
       "      <td>94.0</td>\n",
       "      <td>16.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>Mississippi</td>\n",
       "      <td>0.19</td>\n",
       "      <td>4.0</td>\n",
       "      <td>10.15</td>\n",
       "      <td>14.0</td>\n",
       "      <td>-38.04</td>\n",
       "      <td>8.0</td>\n",
       "      <td>26.0</td>\n",
       "      <td>48.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>Missouri</td>\n",
       "      <td>1.71</td>\n",
       "      <td>15.0</td>\n",
       "      <td>11.40</td>\n",
       "      <td>24.0</td>\n",
       "      <td>-50.91</td>\n",
       "      <td>32.0</td>\n",
       "      <td>71.0</td>\n",
       "      <td>32.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>Montana</td>\n",
       "      <td>5.24</td>\n",
       "      <td>35.0</td>\n",
       "      <td>14.50</td>\n",
       "      <td>39.0</td>\n",
       "      <td>-55.71</td>\n",
       "      <td>48.0</td>\n",
       "      <td>122.0</td>\n",
       "      <td>5.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>Nebraska</td>\n",
       "      <td>4.20</td>\n",
       "      <td>30.0</td>\n",
       "      <td>13.42</td>\n",
       "      <td>35.0</td>\n",
       "      <td>-46.72</td>\n",
       "      <td>26.0</td>\n",
       "      <td>91.0</td>\n",
       "      <td>18.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>Nevada</td>\n",
       "      <td>10.09</td>\n",
       "      <td>46.0</td>\n",
       "      <td>10.64</td>\n",
       "      <td>17.0</td>\n",
       "      <td>-52.98</td>\n",
       "      <td>41.0</td>\n",
       "      <td>104.0</td>\n",
       "      <td>11.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>New Hampshire</td>\n",
       "      <td>1.87</td>\n",
       "      <td>16.0</td>\n",
       "      <td>10.65</td>\n",
       "      <td>18.0</td>\n",
       "      <td>-44.61</td>\n",
       "      <td>24.0</td>\n",
       "      <td>58.0</td>\n",
       "      <td>36.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>New Jersey</td>\n",
       "      <td>2.09</td>\n",
       "      <td>20.0</td>\n",
       "      <td>12.60</td>\n",
       "      <td>31.0</td>\n",
       "      <td>-51.28</td>\n",
       "      <td>34.5</td>\n",
       "      <td>85.5</td>\n",
       "      <td>22.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>New Mexico</td>\n",
       "      <td>0.28</td>\n",
       "      <td>6.0</td>\n",
       "      <td>5.89</td>\n",
       "      <td>1.0</td>\n",
       "      <td>-41.39</td>\n",
       "      <td>15.0</td>\n",
       "      <td>22.0</td>\n",
       "      <td>50.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>New York</td>\n",
       "      <td>1.97</td>\n",
       "      <td>19.0</td>\n",
       "      <td>9.44</td>\n",
       "      <td>11.0</td>\n",
       "      <td>-42.62</td>\n",
       "      <td>19.0</td>\n",
       "      <td>49.0</td>\n",
       "      <td>40.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>North Carolina</td>\n",
       "      <td>6.39</td>\n",
       "      <td>39.0</td>\n",
       "      <td>16.33</td>\n",
       "      <td>48.0</td>\n",
       "      <td>-54.87</td>\n",
       "      <td>44.0</td>\n",
       "      <td>131.0</td>\n",
       "      <td>4.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>North Dakota</td>\n",
       "      <td>10.45</td>\n",
       "      <td>50.0</td>\n",
       "      <td>17.34</td>\n",
       "      <td>51.0</td>\n",
       "      <td>-6.77</td>\n",
       "      <td>2.0</td>\n",
       "      <td>103.0</td>\n",
       "      <td>13.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>Ohio</td>\n",
       "      <td>0.98</td>\n",
       "      <td>11.0</td>\n",
       "      <td>13.37</td>\n",
       "      <td>34.0</td>\n",
       "      <td>-50.53</td>\n",
       "      <td>30.0</td>\n",
       "      <td>75.0</td>\n",
       "      <td>30.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>Oklahoma</td>\n",
       "      <td>3.68</td>\n",
       "      <td>26.0</td>\n",
       "      <td>7.15</td>\n",
       "      <td>5.0</td>\n",
       "      <td>-28.82</td>\n",
       "      <td>5.0</td>\n",
       "      <td>36.0</td>\n",
       "      <td>45.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>Oregon</td>\n",
       "      <td>7.00</td>\n",
       "      <td>40.0</td>\n",
       "      <td>14.99</td>\n",
       "      <td>43.0</td>\n",
       "      <td>-57.44</td>\n",
       "      <td>50.0</td>\n",
       "      <td>133.0</td>\n",
       "      <td>3.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>Pennsylvania</td>\n",
       "      <td>0.49</td>\n",
       "      <td>7.0</td>\n",
       "      <td>16.60</td>\n",
       "      <td>50.0</td>\n",
       "      <td>-43.54</td>\n",
       "      <td>21.0</td>\n",
       "      <td>78.0</td>\n",
       "      <td>28.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>Rhode Island</td>\n",
       "      <td>0.79</td>\n",
       "      <td>9.0</td>\n",
       "      <td>7.39</td>\n",
       "      <td>6.0</td>\n",
       "      <td>-44.28</td>\n",
       "      <td>23.0</td>\n",
       "      <td>38.0</td>\n",
       "      <td>44.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>South Carolina</td>\n",
       "      <td>7.38</td>\n",
       "      <td>41.0</td>\n",
       "      <td>16.20</td>\n",
       "      <td>46.0</td>\n",
       "      <td>-51.28</td>\n",
       "      <td>34.5</td>\n",
       "      <td>121.5</td>\n",
       "      <td>6.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>South Dakota</td>\n",
       "      <td>5.53</td>\n",
       "      <td>36.0</td>\n",
       "      <td>6.61</td>\n",
       "      <td>3.0</td>\n",
       "      <td>-35.48</td>\n",
       "      <td>7.0</td>\n",
       "      <td>46.0</td>\n",
       "      <td>41.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>Tennessee</td>\n",
       "      <td>4.88</td>\n",
       "      <td>33.0</td>\n",
       "      <td>15.79</td>\n",
       "      <td>45.0</td>\n",
       "      <td>-53.33</td>\n",
       "      <td>42.0</td>\n",
       "      <td>120.0</td>\n",
       "      <td>7.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>Texas</td>\n",
       "      <td>10.24</td>\n",
       "      <td>49.0</td>\n",
       "      <td>11.84</td>\n",
       "      <td>25.0</td>\n",
       "      <td>-39.34</td>\n",
       "      <td>10.0</td>\n",
       "      <td>84.0</td>\n",
       "      <td>23.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>Utah</td>\n",
       "      <td>10.10</td>\n",
       "      <td>47.0</td>\n",
       "      <td>16.30</td>\n",
       "      <td>47.0</td>\n",
       "      <td>-55.22</td>\n",
       "      <td>46.0</td>\n",
       "      <td>140.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>Vermont</td>\n",
       "      <td>-0.44</td>\n",
       "      <td>3.0</td>\n",
       "      <td>8.09</td>\n",
       "      <td>8.0</td>\n",
       "      <td>-41.25</td>\n",
       "      <td>14.0</td>\n",
       "      <td>25.0</td>\n",
       "      <td>49.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>Virginia</td>\n",
       "      <td>4.61</td>\n",
       "      <td>32.0</td>\n",
       "      <td>10.23</td>\n",
       "      <td>15.0</td>\n",
       "      <td>-39.21</td>\n",
       "      <td>9.0</td>\n",
       "      <td>56.0</td>\n",
       "      <td>38.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>Washington</td>\n",
       "      <td>8.43</td>\n",
       "      <td>44.0</td>\n",
       "      <td>11.15</td>\n",
       "      <td>22.0</td>\n",
       "      <td>-52.26</td>\n",
       "      <td>37.0</td>\n",
       "      <td>103.0</td>\n",
       "      <td>13.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>West Virginia</td>\n",
       "      <td>-2.13</td>\n",
       "      <td>1.0</td>\n",
       "      <td>9.47</td>\n",
       "      <td>12.0</td>\n",
       "      <td>-24.60</td>\n",
       "      <td>4.0</td>\n",
       "      <td>17.0</td>\n",
       "      <td>51.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>Wisconsin</td>\n",
       "      <td>1.47</td>\n",
       "      <td>13.0</td>\n",
       "      <td>14.72</td>\n",
       "      <td>42.0</td>\n",
       "      <td>-57.35</td>\n",
       "      <td>49.0</td>\n",
       "      <td>104.0</td>\n",
       "      <td>11.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>Wyoming</td>\n",
       "      <td>1.96</td>\n",
       "      <td>18.0</td>\n",
       "      <td>12.01</td>\n",
       "      <td>27.0</td>\n",
       "      <td>1.19</td>\n",
       "      <td>1.0</td>\n",
       "      <td>46.0</td>\n",
       "      <td>41.5</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                   State  Population Change  Population Score  \\\n",
       "0                Alabama               1.50              14.0   \n",
       "1                 Alaska               2.36              23.0   \n",
       "2                Arizona               8.23              42.0   \n",
       "3               Arkansas               2.26              21.0   \n",
       "4             California               4.89              34.0   \n",
       "5               Colorado               9.58              45.0   \n",
       "6            Connecticut               0.21               5.0   \n",
       "7               Delaware               6.04              37.0   \n",
       "8   District of Columbia              12.29              51.0   \n",
       "9                Florida              10.11              48.0   \n",
       "10               Georgia               6.26              38.0   \n",
       "11                Hawaii               3.84              27.5   \n",
       "12                 Idaho               8.33              43.0   \n",
       "13              Illinois              -0.52               2.0   \n",
       "14               Indiana               2.30              22.0   \n",
       "15                  Iowa               2.72              25.0   \n",
       "16                Kansas               1.46              12.0   \n",
       "17              Kentucky               1.94              17.0   \n",
       "18             Louisiana               2.39              24.0   \n",
       "19                 Maine               0.58               8.0   \n",
       "20              Maryland               3.84              27.5   \n",
       "21         Massachusetts               4.13              29.0   \n",
       "22              Michigan               0.87              10.0   \n",
       "23             Minnesota               4.34              31.0   \n",
       "24           Mississippi               0.19               4.0   \n",
       "25              Missouri               1.71              15.0   \n",
       "26               Montana               5.24              35.0   \n",
       "27              Nebraska               4.20              30.0   \n",
       "28                Nevada              10.09              46.0   \n",
       "29         New Hampshire               1.87              16.0   \n",
       "30            New Jersey               2.09              20.0   \n",
       "31            New Mexico               0.28               6.0   \n",
       "32              New York               1.97              19.0   \n",
       "33        North Carolina               6.39              39.0   \n",
       "34          North Dakota              10.45              50.0   \n",
       "35                  Ohio               0.98              11.0   \n",
       "36              Oklahoma               3.68              26.0   \n",
       "37                Oregon               7.00              40.0   \n",
       "38          Pennsylvania               0.49               7.0   \n",
       "39          Rhode Island               0.79               9.0   \n",
       "40        South Carolina               7.38              41.0   \n",
       "41          South Dakota               5.53              36.0   \n",
       "42             Tennessee               4.88              33.0   \n",
       "43                 Texas              10.24              49.0   \n",
       "44                  Utah              10.10              47.0   \n",
       "45               Vermont              -0.44               3.0   \n",
       "46              Virginia               4.61              32.0   \n",
       "47            Washington               8.43              44.0   \n",
       "48         West Virginia              -2.13               1.0   \n",
       "49             Wisconsin               1.47              13.0   \n",
       "50               Wyoming               1.96              18.0   \n",
       "\n",
       "    Education Change  Education Score  Unemployment Change  \\\n",
       "0              14.64             40.0               -49.48   \n",
       "1               8.86              9.0               -14.30   \n",
       "2              10.47             16.0               -47.97   \n",
       "3              15.28             44.0               -40.39   \n",
       "4              10.99             21.0               -52.08   \n",
       "5              12.36             30.0               -54.73   \n",
       "6               6.98              4.0               -42.48   \n",
       "7               9.12             10.0               -40.99   \n",
       "8               9.48             13.0               -42.18   \n",
       "9              14.70             41.0               -55.67   \n",
       "10             12.14             29.0               -52.57   \n",
       "11             13.58             36.0               -45.74   \n",
       "12              6.09              2.0               -58.55   \n",
       "13             10.98             20.0               -44.22   \n",
       "14             16.54             49.0               -52.55   \n",
       "15             12.12             28.0               -40.53   \n",
       "16             11.91             26.0               -43.48   \n",
       "17             13.67             38.0               -47.10   \n",
       "18             12.70             32.0               -29.35   \n",
       "19             12.91             33.0               -50.99   \n",
       "20              7.56              7.0               -41.45   \n",
       "21             10.84             19.0               -50.65   \n",
       "22             13.61             37.0               -54.94   \n",
       "23             11.36             23.0               -52.94   \n",
       "24             10.15             14.0               -38.04   \n",
       "25             11.40             24.0               -50.91   \n",
       "26             14.50             39.0               -55.71   \n",
       "27             13.42             35.0               -46.72   \n",
       "28             10.64             17.0               -52.98   \n",
       "29             10.65             18.0               -44.61   \n",
       "30             12.60             31.0               -51.28   \n",
       "31              5.89              1.0               -41.39   \n",
       "32              9.44             11.0               -42.62   \n",
       "33             16.33             48.0               -54.87   \n",
       "34             17.34             51.0                -6.77   \n",
       "35             13.37             34.0               -50.53   \n",
       "36              7.15              5.0               -28.82   \n",
       "37             14.99             43.0               -57.44   \n",
       "38             16.60             50.0               -43.54   \n",
       "39              7.39              6.0               -44.28   \n",
       "40             16.20             46.0               -51.28   \n",
       "41              6.61              3.0               -35.48   \n",
       "42             15.79             45.0               -53.33   \n",
       "43             11.84             25.0               -39.34   \n",
       "44             16.30             47.0               -55.22   \n",
       "45              8.09              8.0               -41.25   \n",
       "46             10.23             15.0               -39.21   \n",
       "47             11.15             22.0               -52.26   \n",
       "48              9.47             12.0               -24.60   \n",
       "49             14.72             42.0               -57.35   \n",
       "50             12.01             27.0                 1.19   \n",
       "\n",
       "    Unemployment Score  Composite Score  Composite Rank  \n",
       "0                 29.0             83.0            24.0  \n",
       "1                  3.0             35.0            46.0  \n",
       "2                 28.0             86.0            21.0  \n",
       "3                 11.0             76.0            29.0  \n",
       "4                 36.0             91.0            18.5  \n",
       "5                 43.0            118.0             8.0  \n",
       "6                 18.0             27.0            47.0  \n",
       "7                 13.0             60.0            35.0  \n",
       "8                 17.0             81.0            26.0  \n",
       "9                 47.0            136.0             2.0  \n",
       "10                39.0            106.0            10.0  \n",
       "11                25.0             88.5            20.0  \n",
       "12                51.0             96.0            15.0  \n",
       "13                22.0             44.0            43.0  \n",
       "14                38.0            109.0             9.0  \n",
       "15                12.0             65.0            33.0  \n",
       "16                20.0             58.0            36.5  \n",
       "17                27.0             82.0            25.0  \n",
       "18                 6.0             62.0            34.0  \n",
       "19                33.0             74.0            31.0  \n",
       "20                16.0             50.5            39.0  \n",
       "21                31.0             79.0            27.0  \n",
       "22                45.0             92.0            17.0  \n",
       "23                40.0             94.0            16.0  \n",
       "24                 8.0             26.0            48.0  \n",
       "25                32.0             71.0            32.0  \n",
       "26                48.0            122.0             5.0  \n",
       "27                26.0             91.0            18.5  \n",
       "28                41.0            104.0            11.5  \n",
       "29                24.0             58.0            36.5  \n",
       "30                34.5             85.5            22.0  \n",
       "31                15.0             22.0            50.0  \n",
       "32                19.0             49.0            40.0  \n",
       "33                44.0            131.0             4.0  \n",
       "34                 2.0            103.0            13.5  \n",
       "35                30.0             75.0            30.0  \n",
       "36                 5.0             36.0            45.0  \n",
       "37                50.0            133.0             3.0  \n",
       "38                21.0             78.0            28.0  \n",
       "39                23.0             38.0            44.0  \n",
       "40                34.5            121.5             6.0  \n",
       "41                 7.0             46.0            41.5  \n",
       "42                42.0            120.0             7.0  \n",
       "43                10.0             84.0            23.0  \n",
       "44                46.0            140.0             1.0  \n",
       "45                14.0             25.0            49.0  \n",
       "46                 9.0             56.0            38.0  \n",
       "47                37.0            103.0            13.5  \n",
       "48                 4.0             17.0            51.0  \n",
       "49                49.0            104.0            11.5  \n",
       "50                 1.0             46.0            41.5  "
      ]
     },
     "execution_count": 27,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Merge 2 dataframes\n",
    "census_merged = pd.merge(census_2011, census_2017, how=\"inner\",on=\"State\",suffixes=(\"_2011\", \"_2017\"))\n",
    "\n",
    "# Remove Puerto Rico\n",
    "census_merged = census_merged[census_merged.State != \"Puerto Rico\"]\n",
    "census_merged\n",
    "\n",
    "# Reorder Columns for Readability\n",
    "census_merged = census_merged[[\"State\", \"Population_2011\", \"Population_2017\", \"Bachelors Rate_2011\", \"Bachelors Rate_2017\",\"Unemployment Rate_2011\", \"Unemployment Rate_2017\"]]\n",
    "\n",
    "# Calculate percent change between years for each metric\n",
    "census_merged[\"Population Change\"]=round((((census_merged[\"Population_2017\"]-census_merged[\"Population_2011\"])/census_merged[\"Population_2011\"])*100),2)\n",
    "census_merged[\"Education Change\"]=round((((census_merged[\"Bachelors Rate_2017\"]-census_merged[\"Bachelors Rate_2011\"])/census_merged[\"Bachelors Rate_2011\"])*100),2)\n",
    "census_merged[\"Unemployment Change\"]=round((((census_merged[\"Unemployment Rate_2017\"]-census_merged[\"Unemployment Rate_2011\"])/census_merged[\"Unemployment Rate_2011\"])*100),2)\n",
    "\n",
    "# Reorder Columns for Readability\n",
    "census_merged=census_merged[[\"State\",\"Population Change\", \"Education Change\", \"Unemployment Change\"]]\n",
    "\n",
    "# rank order each metric\n",
    "census_merged[\"Population Score\"]= census_merged[\"Population Change\"].rank()\n",
    "census_merged[\"Education Score\"]= census_merged[\"Education Change\"].rank()\n",
    "census_merged[\"Unemployment Score\"]=census_merged[\"Unemployment Change\"].rank(ascending=False)\n",
    "\n",
    "# Reorder Columns for Readability\n",
    "census_merged=census_merged[[\"State\",\"Population Change\", \"Population Score\", \"Education Change\",\"Education Score\", \"Unemployment Change\", \"Unemployment Score\"]]\n",
    "census_merged[\"Composite Score\"]=census_merged[\"Population Score\"]+census_merged[\"Education Score\"]+census_merged[\"Unemployment Score\"]\n",
    "census_merged[\"Composite Rank\"]=census_merged[\"Composite Score\"].rank(ascending=False)\n",
    "census_merged"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "f31951a361394b3fa29fe2cc4adb524c",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Begin Building Gmaps states layer\n",
    "states_geojson = gmaps.geojson_geometries.load_geometry('us-states')\n",
    "fig=gmaps.figure()\n",
    "unemployment_layer = gmaps.geojson_layer(states_geojson)\n",
    "fig.add_layer(unemployment_layer)\n",
    "\n",
    "fig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Transform dataframe into dictionary in order to allow gmaps to iterate through\n",
    "censusdict = census_merged[[\"State\", \"Unemployment Change\"]]\n",
    "censusdict.set_index(\"State\", inplace=True)\n",
    "censusdict2 = censusdict.to_dict()\n",
    "# censusdict2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "20d6f9fdad5a43608841d6315cd18a73",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Scale the values\n",
    "# Note: When negative values are better, use the inverse function for min/max\n",
    "min_unemployment = max(census_merged[\"Unemployment Change\"])\n",
    "max_unemployment = min(census_merged[\"Unemployment Change\"])\n",
    "unemployment_range = min_unemployment - max_unemployment\n",
    "\n",
    "# Create a function to transform the values into a color\n",
    "def calculate_color(unemployment):\n",
    "#     Make the unemployment change a number between 0 and 1\n",
    "    normalized_unemployment = (unemployment - max_unemployment)/unemployment_range\n",
    "#     invert unemployment to make worse performers blue, high performers red\n",
    "    inverse_unemployment = 1.0 - normalized_unemployment\n",
    "#     transform the unemployment numbers to a matplotlib color\n",
    "    mpl_color = coolwarm(inverse_unemployment)\n",
    "#     transform from a matplotlib color to a valid CSS color\n",
    "    gmaps_color = to_hex(mpl_color, keep_alpha=False)\n",
    "    \n",
    "    return gmaps_color\n",
    "    \n",
    "# Loop through each state to build an array of colors\n",
    "colors = []\n",
    "for feature in states_geojson['features']:\n",
    "    state_name = feature[\"properties\"][\"NAME\"]\n",
    "    try:\n",
    "        unemployment = censusdict2[\"Unemployment Change\"][state_name]\n",
    "        color = calculate_color(unemployment)\n",
    "    except (KeyError):\n",
    "        color = (0,0,0,0.3)\n",
    "    colors.append(color)\n",
    "\n",
    "# Build map\n",
    "fig=gmaps.figure()\n",
    "unemployment_layer = gmaps.geojson_layer(states_geojson,fill_color=colors,stroke_color=colors,fill_opacity=0.8)\n",
    "fig.add_layer(unemployment_layer)\n",
    "fig\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [],
   "source": [
    "censusdict_edu = census_merged[[\"State\", \"Education Change\"]]\n",
    "censusdict_edu.set_index(\"State\", inplace=True)\n",
    "censusdict_edu2 = censusdict_edu.to_dict()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "542436cd48d9400b8ba6354535462b80",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Scale the values\n",
    "# Note: When negative values are better, use the inverse function for min/max\n",
    "min_education = min(census_merged[\"Education Change\"])\n",
    "max_education = max(census_merged[\"Education Change\"])\n",
    "education_range = max_education - min_education\n",
    "\n",
    "# Create a function to transform the values into a color\n",
    "def calculate_education(education):\n",
    "    normalized_education = (education - min_education)/education_range\n",
    "    mpl_color = coolwarm(normalized_education)\n",
    "    gmaps_color = to_hex(mpl_color, keep_alpha=False)\n",
    "    \n",
    "    return gmaps_color\n",
    "\n",
    "# Loop through each state to build an array of colors\n",
    "education_colors = []\n",
    "for feature in states_geojson['features']:\n",
    "    state_name = feature[\"properties\"][\"NAME\"]\n",
    "    try:\n",
    "        education = censusdict_edu2[\"Education Change\"][state_name]\n",
    "        color = calculate_education(education)\n",
    "    except (KeyError):\n",
    "        color = (0,0,0,0.3)\n",
    "    education_colors.append(color)\n",
    "\n",
    "\n",
    "# Build map\n",
    "fig=gmaps.figure()\n",
    "education_layer = gmaps.geojson_layer(states_geojson,fill_color=education_colors,stroke_color=education_colors,fill_opacity=0.8)\n",
    "fig.add_layer(education_layer)\n",
    "fig\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [],
   "source": [
    "censusdict_comp = census_merged[[\"State\", \"Composite Score\"]]\n",
    "censusdict_comp.set_index(\"State\", inplace=True)\n",
    "censusdict_comp2 = censusdict_comp.to_dict()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "afbe97d7edda40fb80f9897eaa3fcf8e",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Scale the values\n",
    "# Note: When negative values are better, use the inverse function for min/max\n",
    "min_comp = min(census_merged[\"Composite Score\"])\n",
    "max_comp = max(census_merged[\"Composite Score\"])\n",
    "comp_range = max_comp - min_comp\n",
    "\n",
    "# Create a function to transform the values into a color\n",
    "def calculate_composite(composite):\n",
    "    normalized_comp = (composite - min_comp)/comp_range\n",
    "    mpl_color = coolwarm(normalized_comp)\n",
    "    gmaps_color = to_hex(mpl_color, keep_alpha=False)\n",
    "    \n",
    "    return gmaps_color\n",
    "\n",
    "# Loop through each state to build an array of colors\n",
    "comp_colors = []\n",
    "for feature in states_geojson['features']:\n",
    "    state_name = feature[\"properties\"][\"NAME\"]\n",
    "    try:\n",
    "        composite = censusdict_comp2[\"Composite Score\"][state_name]\n",
    "        color = calculate_composite(composite)\n",
    "    except (KeyError):\n",
    "        color = (0,0,0,0.3)\n",
    "    comp_colors.append(color)\n",
    "\n",
    "\n",
    "# Build map\n",
    "fig=gmaps.figure()\n",
    "comp_layer = gmaps.geojson_layer(states_geojson,fill_color=comp_colors,stroke_color=comp_colors,fill_opacity=0.8)\n",
    "fig.add_layer(comp_layer)\n",
    "fig\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "censusdict_pop = census_merged[[\"State\", \"Population Change\"]]\n",
    "censusdict_pop.set_index(\"State\", inplace=True)\n",
    "censusdict_pop2 = censusdict_pop.to_dict()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "2ae9249d42a04164b2209634fce7d217",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Figure(layout=FigureLayout(height='420px'))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Scale the values\n",
    "# Note: When negative values are better, use the inverse function for min/max\n",
    "min_pop = min(census_merged[\"Population Change\"])\n",
    "max_pop = max(census_merged[\"Population Change\"])\n",
    "pop_range = max_pop - min_pop\n",
    "\n",
    "# Create a function to transform the values into a color\n",
    "def calculate_pop(pop):\n",
    "    normalized_pop = (pop - min_pop)/pop_range\n",
    "    mpl_color = coolwarm(normalized_pop)\n",
    "    gmaps_color = to_hex(mpl_color, keep_alpha=False)\n",
    "    \n",
    "    return gmaps_color\n",
    "\n",
    "# Loop through each state to build an array of colors\n",
    "pop_colors = []\n",
    "for feature in states_geojson['features']:\n",
    "    state_name = feature[\"properties\"][\"NAME\"]\n",
    "    try:\n",
    "        pop = censusdict_pop2[\"Population Change\"][state_name]\n",
    "        color = calculate_pop(pop)\n",
    "    except (KeyError):\n",
    "        color = (0,0,0,0.3)\n",
    "    pop_colors.append(color)\n",
    "    \n",
    "\n",
    "\n",
    "# Build map\n",
    "fig=gmaps.figure()\n",
    "pop_layer = gmaps.geojson_layer(states_geojson,fill_color=pop_colors,stroke_color=pop_colors,fill_opacity=0.8)\n",
    "fig.add_layer(pop_layer)\n",
    "fig\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:PythonData]",
   "language": "python",
   "name": "conda-env-PythonData-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
